# Generated by Django 4.2.4 on 2023-09-24 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_bloodrequest_is_immediate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodrequest',
            name='email',
        ),
        migrations.RemoveField(
            model_name='bloodrequest',
            name='phone',
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
