# Generated by Django 4.2.4 on 2023-09-24 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_remove_bloodrequest_email_remove_bloodrequest_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequest',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
