# Generated by Django 4.2.4 on 2023-09-24 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_alter_bloodrequest_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorresponse',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
