# Generated by Django 4.2.4 on 2023-09-26 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_gramapanchayath'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gramapanchayat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('gramapanchayat_id', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Gramapanchayath',
            new_name='AssignGramapanchayath',
        ),
    ]
