# Generated by Django 4.2.4 on 2023-09-26 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_rename_name_gramapanchayat_name_of_gramapanchayath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigngramapanchayath',
            name='gramapanchayat1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment1', to='website.gramapanchayat', unique=True),
        ),
        migrations.AlterField(
            model_name='assigngramapanchayath',
            name='gramapanchayat2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment2', to='website.gramapanchayat', unique=True),
        ),
        migrations.AlterField(
            model_name='assigngramapanchayath',
            name='gramapanchayat3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment3', to='website.gramapanchayat', unique=True),
        ),
        migrations.AlterField(
            model_name='assigngramapanchayath',
            name='gramapanchayat4',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment4', to='website.gramapanchayat', unique=True),
        ),
        migrations.AlterField(
            model_name='assigngramapanchayath',
            name='gramapanchayat5',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment5', to='website.gramapanchayat', unique=True),
        ),
    ]
