# Generated by Django 4.2.4 on 2023-09-26 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_alter_assigngramapanchayath_gramapanchayat1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigngramapanchayath',
            name='gramapanchayat1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment1', to='website.gramapanchayat'),
        ),
        migrations.AlterField(
            model_name='assigngramapanchayath',
            name='gramapanchayat2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment2', to='website.gramapanchayat'),
        ),
        migrations.AlterField(
            model_name='assigngramapanchayath',
            name='gramapanchayat3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment3', to='website.gramapanchayat'),
        ),
        migrations.AlterField(
            model_name='assigngramapanchayath',
            name='gramapanchayat4',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment4', to='website.gramapanchayat'),
        ),
        migrations.AlterField(
            model_name='assigngramapanchayath',
            name='gramapanchayat5',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment5', to='website.gramapanchayat'),
        ),
        migrations.AddConstraint(
            model_name='assigngramapanchayath',
            constraint=models.UniqueConstraint(fields=('staff', 'gramapanchayat1'), name='unique_assignment1'),
        ),
        migrations.AddConstraint(
            model_name='assigngramapanchayath',
            constraint=models.UniqueConstraint(fields=('staff', 'gramapanchayat2'), name='unique_assignment2'),
        ),
        migrations.AddConstraint(
            model_name='assigngramapanchayath',
            constraint=models.UniqueConstraint(fields=('staff', 'gramapanchayat3'), name='unique_assignment3'),
        ),
        migrations.AddConstraint(
            model_name='assigngramapanchayath',
            constraint=models.UniqueConstraint(fields=('staff', 'gramapanchayat4'), name='unique_assignment4'),
        ),
        migrations.AddConstraint(
            model_name='assigngramapanchayath',
            constraint=models.UniqueConstraint(fields=('staff', 'gramapanchayat5'), name='unique_assignment5'),
        ),
    ]
