# Generated by Django 4.2.4 on 2023-09-26 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_alter_assigngramapanchayath_gramapanchayat1_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AssignGramapanchayath',
            new_name='AssignGrampanchayat',
        ),
        migrations.RenameModel(
            old_name='Gramapanchayat',
            new_name='Grampanchayat',
        ),
        migrations.RemoveConstraint(
            model_name='assigngrampanchayat',
            name='unique_assignment1',
        ),
        migrations.RemoveConstraint(
            model_name='assigngrampanchayat',
            name='unique_assignment2',
        ),
        migrations.RemoveConstraint(
            model_name='assigngrampanchayat',
            name='unique_assignment3',
        ),
        migrations.RemoveConstraint(
            model_name='assigngrampanchayat',
            name='unique_assignment4',
        ),
        migrations.RemoveConstraint(
            model_name='assigngrampanchayat',
            name='unique_assignment5',
        ),
        migrations.RenameField(
            model_name='assigngrampanchayat',
            old_name='gramapanchayat1',
            new_name='grampanchayat1',
        ),
        migrations.RenameField(
            model_name='assigngrampanchayat',
            old_name='gramapanchayat2',
            new_name='grampanchayat2',
        ),
        migrations.RenameField(
            model_name='assigngrampanchayat',
            old_name='gramapanchayat3',
            new_name='grampanchayat3',
        ),
        migrations.RenameField(
            model_name='assigngrampanchayat',
            old_name='gramapanchayat4',
            new_name='grampanchayat4',
        ),
        migrations.RenameField(
            model_name='assigngrampanchayat',
            old_name='gramapanchayat5',
            new_name='grampanchayat5',
        ),
        migrations.RenameField(
            model_name='grampanchayat',
            old_name='gramapanchayat_id',
            new_name='grampanchayat_id',
        ),
        migrations.RenameField(
            model_name='grampanchayat',
            old_name='name_of_gramapanchayath',
            new_name='name_of_grampanchayat',
        ),
        migrations.AddConstraint(
            model_name='assigngrampanchayat',
            constraint=models.UniqueConstraint(fields=('staff', 'grampanchayat1'), name='unique_assignment1'),
        ),
        migrations.AddConstraint(
            model_name='assigngrampanchayat',
            constraint=models.UniqueConstraint(fields=('staff', 'grampanchayat2'), name='unique_assignment2'),
        ),
        migrations.AddConstraint(
            model_name='assigngrampanchayat',
            constraint=models.UniqueConstraint(fields=('staff', 'grampanchayat3'), name='unique_assignment3'),
        ),
        migrations.AddConstraint(
            model_name='assigngrampanchayat',
            constraint=models.UniqueConstraint(fields=('staff', 'grampanchayat4'), name='unique_assignment4'),
        ),
        migrations.AddConstraint(
            model_name='assigngrampanchayat',
            constraint=models.UniqueConstraint(fields=('staff', 'grampanchayat5'), name='unique_assignment5'),
        ),
    ]
