# Generated by Django 4.2.4 on 2023-09-28 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_rename_assigngramapanchayath_assigngrampanchayat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigngrampanchayat',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.staff', unique=True),
        ),
    ]
