# Generated by Django 4.2.4 on 2023-10-03 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_alter_assigngrampanchayat_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='id_proof',
            field=models.FileField(blank=True, null=True, upload_to='id_proofs/'),
        ),
    ]
