# Generated by Django 4.2.4 on 2023-10-03 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_alter_donor_gender_alter_donor_id_proof'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='gender',
        ),
    ]
