# Generated by Django 4.2.4 on 2023-10-03 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_remove_donor_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laboratoryName', models.CharField(max_length=255)),
            ],
        ),
    ]
