# Generated by Django 4.2.4 on 2023-10-04 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0030_labselection_upload_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labselection',
            name='upload_date',
        ),
    ]
