# Generated by Django 4.2.4 on 2023-10-06 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0033_uploadedfile_lab_selection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedfile',
            old_name='lab_selection',
            new_name='selected_lab',
        ),
    ]
