# Generated by Django 4.2.4 on 2023-10-06 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0034_rename_lab_selection_uploadedfile_selected_lab'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='selected_lab',
        ),
    ]
