# Generated by Django 4.2.4 on 2023-10-06 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0036_bloodcamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodcamp',
            name='register',
        ),
    ]
