# Generated by Django 4.2.4 on 2023-10-06 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0039_alter_uploadedfile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='user',
        ),
    ]
