# Generated by Django 4.2.4 on 2023-10-08 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0041_uploadedfile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BloodCamp',
        ),
    ]
