# Generated by Django 4.2.4 on 2023-10-08 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0042_delete_bloodcamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodCamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campDate', models.DateField()),
                ('campName', models.CharField(max_length=255)),
                ('campAddress', models.TextField()),
                ('campDistrict', models.CharField(default='Kottayam', max_length=100)),
                ('campContact', models.CharField(max_length=15)),
                ('conductedBy', models.CharField(max_length=255)),
                ('organizedBy', models.CharField(max_length=255)),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
            ],
        ),
    ]
