# Generated by Django 4.2.4 on 2023-10-10 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0045_uploadedfile_approval_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
