# Generated by Django 4.2.4 on 2023-10-10 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0046_uploadedfile_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodcamp',
            name='gramPanchayat',
            field=models.CharField(blank=True, default='DefaultPanchayat', max_length=100, null=True),
        ),
    ]
