# Generated by Django 4.2.4 on 2023-10-12 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0047_alter_bloodcamp_grampanchayat'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodcamp',
            name='endTime2',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='bloodcamp',
            name='startTime2',
            field=models.TimeField(null=True),
        ),
    ]
