# Generated by Django 4.2.4 on 2023-10-13 04:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0048_bloodcamp_endtime2_bloodcamp_starttime2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_time', models.DateTimeField(auto_now_add=True)),
                ('blood_camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.bloodcamp')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.donor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
