# Generated by Django 4.2.4 on 2023-10-13 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0049_appointment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
