# Generated by Django 4.2.4 on 2023-10-18 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0051_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('donated', 'Donated'), ('not_donated', 'Not Donated')], max_length=20, null=True, blank=True),
        ),
    ]
