# Generated by Django 4.2.4 on 2023-10-18 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0052_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('donated', 'Donated'), ('not_donated', 'Not Donated')], default='not_donated', max_length=20),
        ),
    ]
