# Generated by Django 4.2.4 on 2023-10-19 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0056_alter_appointment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DontedDonor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('donation_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.donor')),
            ],
        ),
    ]
