# Generated by Django 4.2.4 on 2023-10-21 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0059_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
