# Generated by Django 4.2.4 on 2023-10-21 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0060_bloodrequest_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='razorpay_order_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
