# Generated by Django 4.2.4 on 2023-10-23 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0061_payment_razorpay_order_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonorDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_donation', models.DateField()),
                ('expiry_date', models.DateField()),
                ('sample_name', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='website.appointment')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.donor')),
            ],
        ),
        migrations.DeleteModel(
            name='DonatedDonor',
        ),
    ]
