# Generated by Django 4.2.4 on 2023-10-23 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0062_donordetails_delete_donateddonor'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotDonatedReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='website.appointment')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.donor')),
            ],
        ),
    ]
