# Generated by Django 4.2.4 on 2024-01-09 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0063_notdonatedreason'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodInventory',
            fields=[
                ('blood_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='website.bloodtype')),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
    ]
