# Generated by Django 4.2.4 on 2024-01-22 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0064_bloodinventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaboratoryTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=255)),
                ('test_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('package_details', models.JSONField()),
            ],
        ),
    ]
