# Generated by Django 4.2.4 on 2024-01-30 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0066_patient_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='selected_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.laboratorytest'),
        ),
    ]
