# Generated by Django 4.2.4 on 2024-02-06 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0067_patient_selected_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='role',
            field=models.CharField(blank=True, choices=[(1, 'DONOR'), (2, 'HOSPITAL'), (3, 'STAFF'), (4, 'REGISTEREDDONOR'), (5, 'LABSTAFF')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.IntegerField(choices=[(1, 'DONOR'), (2, 'HOSPITAL'), (3, 'STAFF'), (4, 'REGISTEREDDONOR'), (5, 'LABSTAFF')], default='1'),
        ),
    ]
