# Generated by Django 4.2.4 on 2024-02-07 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0068_staff_role_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequest',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
