# Generated by Django 5.0.2 on 2024-02-12 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0072_booking_booking_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='booking_date',
            new_name='test_date',
        ),
    ]
