# Generated by Django 5.0.2 on 2024-02-14 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0073_rename_booking_date_booking_test_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('booked', 'Booked'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='booked', max_length=20),
        ),
    ]
