# Generated by Django 5.0.2 on 2024-02-19 09:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0075_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequest',
            name='requested_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='requested_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
