# Generated by Django 5.0.2 on 2024-02-28 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0076_alter_bloodrequest_requested_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FBS', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
                ('PPBS', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
                ('HBA1C', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
                ('LIPID', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
                ('TSH', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
                ('UREA', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
                ('CREATININE', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
                ('MICROALBUMINSPOT', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
                ('URINEANALYSIS', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
                ('CBC', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
                ('LFTWITHOUTGGT', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
                ('RENEALPROFILE', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
                ('TFT', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
                ('TIBC', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
                ('VITAMIND', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
                ('ELECTROLYTES', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
                ('TMT', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
                ('USGABDOMENPELVIS', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
                ('MAMMOGRAPHY', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
                ('CYTOLOGYCSPAPSMEAR', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
                ('URICACID', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
                ('BUN', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
                ('TPC', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
                ('HYDROXYVITAMIND', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
                ('PSA', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
                ('USGTHYROID', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
                ('CALCIUM', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
                ('patient_id', models.IntegerField()),
                ('booking_id', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('blood_request', 'Blood Request'), ('expiry_date', 'Expiry Date')], max_length=50),
        ),
    ]
