# Generated by Django 5.0.2 on 2024-02-28 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0077_labresult_alter_notification_notification_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labresult',
            name='booking_id',
        ),
        migrations.RemoveField(
            model_name='labresult',
            name='patient_id',
        ),
        migrations.AddField(
            model_name='labresult',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.booking'),
        ),
        migrations.AddField(
            model_name='labresult',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab_results', to='website.patient'),
        ),
    ]
