# Generated by Django 5.0.2 on 2024-03-13 17:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0079_patient_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='labresult',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
