# Generated by Django 5.0.2 on 2024-03-26 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0084_remove_labreview_created_at_alter_labreview_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labreview',
            name='patient',
        ),
        migrations.AddField(
            model_name='labreview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
